-- EEL storage schema v1.
--
-- `meta`, `events` and `blocks` are the source of truth and are append-only:
-- triggers abort any UPDATE or DELETE on them. Every other table is a
-- projection of the ontology state, rebuilt after each block, and can always
-- be regenerated by replaying the ledger.

CREATE TABLE meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE events (
    event_id     TEXT PRIMARY KEY,
    position     INTEGER NOT NULL UNIQUE,
    block_height INTEGER NOT NULL,
    event_type   TEXT NOT NULL,
    branch       TEXT NOT NULL,
    author       TEXT NOT NULL,
    timestamp    INTEGER NOT NULL,
    body         TEXT NOT NULL
);

CREATE TABLE blocks (
    height              INTEGER PRIMARY KEY,
    block_hash          TEXT NOT NULL UNIQUE,
    previous_block_hash TEXT NOT NULL,
    timestamp           INTEGER NOT NULL,
    events_root         TEXT NOT NULL,
    state_root          TEXT NOT NULL,
    proposer            TEXT NOT NULL,
    signature           TEXT NOT NULL,
    event_ids           TEXT NOT NULL
);

CREATE TRIGGER meta_no_update BEFORE UPDATE ON meta BEGIN SELECT RAISE(ABORT, 'meta is append-only'); END;
CREATE TRIGGER meta_no_delete BEFORE DELETE ON meta BEGIN SELECT RAISE(ABORT, 'meta is append-only'); END;
CREATE TRIGGER events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT, 'events are append-only'); END;
CREATE TRIGGER events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT, 'events are append-only'); END;
CREATE TRIGGER blocks_no_update BEFORE UPDATE ON blocks BEGIN SELECT RAISE(ABORT, 'blocks are append-only'); END;
CREATE TRIGGER blocks_no_delete BEFORE DELETE ON blocks BEGIN SELECT RAISE(ABORT, 'blocks are append-only'); END;

-- Projections ---------------------------------------------------------------

CREATE TABLE identities (identity_id TEXT PRIMARY KEY, public_key TEXT NOT NULL, created_at INTEGER NOT NULL, body TEXT NOT NULL);
CREATE TABLE validators (validator_id TEXT PRIMARY KEY, identity_id TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE branches (branch_id TEXT PRIMARY KEY, parent_branch TEXT, fork_event TEXT, head TEXT, body TEXT NOT NULL);
CREATE TABLE claims (branch TEXT NOT NULL, claim_id TEXT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (branch, claim_id));
CREATE TABLE claim_versions (branch TEXT NOT NULL, claim_id TEXT NOT NULL, version INTEGER NOT NULL, event_id TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (branch, claim_id, version));
CREATE TABLE ontology_edges (branch TEXT NOT NULL, source TEXT NOT NULL, relation TEXT NOT NULL, target TEXT NOT NULL, originating_event TEXT NOT NULL);
CREATE TABLE evidence (branch TEXT NOT NULL, evidence_id TEXT NOT NULL, claim_id TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (branch, evidence_id));
CREATE TABLE objections (branch TEXT NOT NULL, objection_id TEXT NOT NULL, resolved INTEGER NOT NULL, body TEXT NOT NULL, PRIMARY KEY (branch, objection_id));
CREATE TABLE validations (branch TEXT NOT NULL, validation_id TEXT NOT NULL, validator TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (branch, validation_id));
CREATE TABLE canonicalization_proposals (branch TEXT NOT NULL, proposal_id TEXT NOT NULL, state TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY (branch, proposal_id));
CREATE TABLE artifacts (artifact_id TEXT PRIMARY KEY, uri TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE xchange_assets (asset_id TEXT PRIMARY KEY, asset_type TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE research_requests (request_id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE support_commitments (request_id TEXT NOT NULL, seq INTEGER NOT NULL, supporter TEXT NOT NULL, amount_units INTEGER NOT NULL, body TEXT NOT NULL, PRIMARY KEY (request_id, seq));
CREATE TABLE research_results (event_id TEXT PRIMARY KEY, request_id TEXT NOT NULL, credited INTEGER NOT NULL, body TEXT NOT NULL);
CREATE TABLE simulation_jobs (job_id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE simulation_results (result_id TEXT PRIMARY KEY, job_id TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE simulation_verifications (result_id TEXT NOT NULL, validator TEXT NOT NULL, reproduced INTEGER NOT NULL, PRIMARY KEY (result_id, validator));
